<?php

namespace Netpublic\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnoGradoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnoGradoRepository extends EntityRepository
{
}
