<?php

namespace Netpublic\RedsaberBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlumnoexamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumnoexamenRepository extends EntityRepository
{
           public function findPreguntaGrupo($alumno_id,$examen_id){
            $em=  $this->getEntityManager();
            $query="SELECT b,p FROM NetpublicRedsaberBundle:Pregunta p JOIN .pregunta p JOIN p.examen e ";
            $query.=" WHERE (";
            $query.=" p.alumno_referencia=:alumno_id";
            $query.=" AND e.id=:examen_id";
            $query.=" )"; 
            $query.=" ORDER BY p.bloque ASC,b.label ASC,";            
            $query.=" p.indice ASC";
            
            //$query.=" ORDER BY a.apellido ASC, a.apellido1, a.nombre,a.nombre1 DESC ";
            $entities=$em->createQuery($query)                
                                 ->setParameters(array(
                                         "alumno_id"=>$alumno_id,
                                         "examen_id"=>$examen_id
                                         ))->getResult(); 


            return $entities;  
    }

}
