<?php

namespace Netpublic\RedsaberBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BubleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BubleRepository extends EntityRepository
{
     public function findPreguntasPorPorcentaje($examen_id,$limite_inferior,$limite_superior){
            $em=  $this->getEntityManager();
            $query="SELECT b,p FROM NetpublicRedsaberBundle:Buble b JOIN b.respuesta p ";
            $query.=" WHERE (";
            $query.=" b.estado>=:limite_inferior ";
            $query.=" AND b.estado<=:limite_superior ";
            $query.=" AND p.examen=:examen_id ";
            $query.=" AND p.tipo=2 ";
            $query.=" )"; 
            $entities=$em->createQuery($query)                
                                 ->setParameters(array(
                                        "examen_id"=>$examen_id,
                                        "limite_inferior"=>$limite_inferior,
                                        "limite_superior"=>$limite_superior
                                         ))->getResult(); 
            return $entities;  
    }
   
    public function findPreguntasExamen($pregunta){
            $em=  $this->getEntityManager();
            $query="SELECT b FROM NetpublicRedsaberBundle:Buble b JOIN b.respuesta p ";
            $query.=" WHERE (";
            $query.=" b.estado>0 ";
            $query.=" AND p.tipo=2 ";  
            $query.=" AND p.id=:pregunta_id ";
            $query.=" )"; 
            $entities=$em->createQuery($query)                
                                 ->setParameters(array(
                                       "pregunta_id"=>$pregunta->getId()
                                         ))->getResult();
                         
            
            return $entities[0];  
    }
    public function findBubleExamen($pregunta,$label){
            $em=  $this->getEntityManager();
            $query="SELECT b FROM NetpublicRedsaberBundle:Buble b JOIN b.respuesta p ";
            $query.=" WHERE (";
            $query.=" b.label=:label ";
            $query.=" AND p.tipo=2 ";       
            $query.=" AND p.indice=:indice ";
            $query.=" AND p.examen=:examen_id ";
            $query.=" )"; 
            $entities=$em->createQuery($query)                
                                 ->setParameters(array(
                                       "indice"=>$pregunta->getIndice(),
                                       "label"=>$label,
                                        "examen_id"=>$pregunta->getExamen()->getId()
                                         ))->getOneOrNullResult(); 
            return $entities;  
    }
    public function findBublePorcentaje($pregunta,$label){
            $em=  $this->getEntityManager();
            $query="SELECT b FROM NetpublicRedsaberBundle:Buble b JOIN b.respuesta p ";
            $query.=" WHERE (";
            $query.=" b.label=:label ";
            $query.=" AND p.tipo=2 ";       
            $query.=" AND p.examen=:examen_id ";       
            $query.=" AND p.indice=:indice";
            $query.=" )"; 
            $entities=$em->createQuery($query)                
                                 ->setParameters(array(
                                       "indice"=>$pregunta->getIndice(),
                                       "examen_id"=>$pregunta->getExamen()->getId(),
                                       "label"=>$label
                                         ))->getOneOrNullResult(); 
            
            return $entities;  
    }
    public function findPreguntaIndice($pregunta,$tipo){
            $em=  $this->getEntityManager();
            $query="SELECT p FROM NetpublicRedsaberBundle:Respueta p ";
            $query.=" WHERE (";
            $query.=" p.tipo=:tipo ";       
            $query.=" AND p.examen=:examen_id ";       
            $query.=" AND p.indice=:indice";
            $query.=" )"; 
            $entities=$em->createQuery($query)                
                                 ->setParameters(array(
                                       "indice"=>$pregunta->getIndice(),
                                       "tipo"=>$tipo,
                                       "examen_id"=>$pregunta->getExamen()->getId(),
                                       ))->getOneOrNullResult(); 
            return $entities;  
    }
    public function findBuble($examen_id,$indice,$label,$tipo){
            $em=  $this->getEntityManager();
            $query="SELECT b,p FROM NetpublicRedsaberBundle:Buble b JOIN b.respuesta p ";
            $query.=" WHERE (";
            $query.=" p.tipo=:tipo ";       
            $query.=" AND p.examen=:examen_id ";       
            $query.=" AND p.indice=:indice";
            $query.=" AND b.label=:label";
            $query.=" )"; 
            $entities=$em->createQuery($query)                
                                 ->setParameters(array(
                                       "indice"=>$indice,
                                       "tipo"=>$tipo,
                                       "examen_id"=>$examen_id,
                                       "label"=>$label
                                       ))->getOneOrNullResult(); 
            return $entities;  
    }

    public function findNroAlumnosNivelComplejidadBuble($examen_id,$limite_inferior,$limite_superior){
            $em=  $this->getEntityManager();
            $query="SELECT b,p FROM NetpublicRedsaberBundle:Buble b JOIN b.respuesta p ";
            $query.=" WHERE (";
            $query.=" p.tipo=:tipo ";       
            $query.=" AND p.examen=:examen_id ";       
            $query.=" AND p.indice=:indice";
            $query.=" AND b.label=:label";
            $query.=" )"; 
            $entities=$em->createQuery($query)                
                                 ->setParameters(array(
                                       "indice"=>$indice,
                                       "tipo"=>$tipo,
                                       "examen_id"=>$examen_id,
                                       "label"=>$label
                                       ))->getOneOrNullResult(); 
            return $entities;  
    }
    public function findPreguntaIndiceTodosAlumnos($pregunta){
            $em=  $this->getEntityManager();
            $query="SELECT b,r FROM NetpublicRedsaberBundle:Buble b JOIN b.respuesta r";
            $query.=" WHERE (";
            $query.=" r.tipo=1 ";       
            $query.=" AND r.examen=:examen_id ";       
            $query.=" AND r.indice=:indice";            
            $query.=" )"; 
            $query.="ORDER BY r.alumno_referencia DESC";
            $entities=$em->createQuery($query)                
                                 ->setParameters(array(
                                       "indice"=>$pregunta->getIndice(),                                      
                                       "examen_id"=>$pregunta->getExamen()->getId(),
                                       ))->getResult(); 
            return $entities;  
    }


  
}
