<?php

namespace Netpublic\RedsaberBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComponenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponenteRepository extends EntityRepository
{
    function findComponentePadre($grado_id) {
        $em=  $this->getEntityManager();
        $query="SELECT c FROM NetpublicRedsaberBundle:Componente c ";
        $query.=" WHERE (";
        $query.=" c.grado=:grado_id ";
        $query.=" AND c.padre is NULL ";
        $query.=" )"; 
        $entities=$em->createQuery($query)                
                              ->setParameters(array(
                                         "grado_id"=>$grado_id
                                         ))->getResult(); 


            return $entities;  
    }
}
