<?php

namespace Netpublic\RedsaberBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExamenicfesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamenicfesRepository extends EntityRepository
{
   public function findTemas($examen_id){
            $em=  $this->getEntityManager();
            $query="SELECT p_e,c,p FROM NetpublicRedsaberBundle:PreguntaExamen p_e JOIN p_e.examen e JOIN p_e.pregunta p JOIN p.temas c ";
            $query.=" WHERE (";            
            $query.=" p_e.examen=:examen_id ";
            $query.=" )"; 
            $entities=$em->createQuery($query)                
                                 ->setParameters(array(
                                       "examen_id"=>$examen_id
                                       ))->getResult(); 
            return $entities;  
    }

    public function findComponente($examen_id){
            $em=  $this->getEntityManager();
            $query="SELECT p_e,c,p FROM NetpublicRedsaberBundle:PreguntaExamen p_e JOIN p_e.examen e JOIN p_e.pregunta p JOIN p.componente c ";
            $query.=" WHERE (";            
            $query.=" p_e.examen=:examen_id ";
            $query.=" )"; 
            $entities=$em->createQuery($query)                
                                 ->setParameters(array(
                                       "examen_id"=>$examen_id
                                       ))->getResult(); 
            return $entities;  
    }

           public function findNroAlumnoExamen($examen_id){
            $em=  $this->getEntityManager();
            $query="SELECT count(a_e) FROM NetpublicRedsaberBundle:AlumnoExamen a_e ";
            $query.=" WHERE (";
            $query.=" a_e.examen=:examen_id ";
            $query.=" )"; 
            $entities=$em->createQuery($query)                
                                 ->setParameters(array(
                                         "examen_id"=>$examen_id
                                         ))->getSingleScalarResult(); 


            return $entities;  
    }

}
