<?php

namespace Netpublic\RedsaberBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlanareaaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanareaaRepository extends EntityRepository
{
    public function findPadres($asignatura_id){
            $em=  $this->getEntityManager();
            $query="SELECT p FROM NetpublicRedsaberBundle:PlanArea p";
            $query.=" WHERE (";
            $query.=" p.asignatura=:asignatura_id AND";
            $query.=" p.padre is null)";
            $entities=$em->createQuery($query)->setParameter('asignatura_id', $asignatura_id)->getResult(); 
            return $entities;  
    }
    public function   findNroTemasTotalesAsg($asigantura_id){
            $em=  $this->getEntityManager();
            $query="SELECT count(p_a) FROM NetpublicRedsaberBundle:PlanArea p_a ";
            $query.=" WHERE (";
            $query.=" p_a.asignatura=:asignatura_id ";
            $query.=" AND p_a.es_ultimo=1 ";
            $query.=" )"; 
            $entities=$em->createQuery($query)                
                                 ->setParameters(array(
                                         "asignatura_id"=>$asigantura_id
                                         ))->getSingleScalarResult(); 


            return $entities;
        
    }

}
