<?php

namespace Netpublic\RedsaberBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TemaevaluadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemaevaluadoRepository extends EntityRepository
{
    public function   findNroTemasEvaluadosAsg($asigantura_id,$ano_escolar_id){
            $em=  $this->getEntityManager();
            $query="SELECT count(t_e) FROM NetpublicRedsaberBundle:TemasEvaluados t_e JOIN t_e.tema t ";
            $query.=" WHERE (";
            $query.=" t.asignatura=:asignatura_id ";
            $query.=" AND t_e.ano_escolar=:ano_escolar_id ";
            $query.=" )"; 
            $entities=$em->createQuery($query)                
                                 ->setParameters(array(
                                         "asignatura_id"=>$asigantura_id,
                                         "ano_escolar_id"=>$ano_escolar_id
                                         ))->getSingleScalarResult(); 


            return $entities;
        
    }
}
