security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        Netpublic\CoreBundle\Entity\Usuario:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        
    providers:
        #in_memory:
        #    users:
        #        user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #         admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        user_db:
            entity: { class: Netpublic\CoreBundle\Entity\Usuario, property: username }

    firewalls:
        main:
            pattern: /.*
            form_login:
                login_path: /login
                check_path: /login_check
                remember_me: false
                default_target_path: /usuario/
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /login
            #remember_me:
            #    key: MiClaveSegura
            #    lifetime: 1800
            #    path: /.*
            #    domain: ~
            security: true
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
         - { path: /_wdt/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: /_profiler/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: /login, role: IS_AUTHENTICATED_ANONYMOUSLY }
         #- { path: /.*, role: IS_AUTHENTICATED_FULLY }
         #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/, roles: ROLE_PROFESORES}
         - { path: ^/, roles: [ROLE_ESTUDIANTE,ROLE_PROFESORES,ROLE_ACUDIENTE,ROLE_RECTOR,ROLE_AUXILIAR,ROLE_COORDINADOR,ROLE_VISITANTE]}
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }