parameters:
#    netpublic_redsaber.example.class: Netpublic\RedsaberBundle\Example

services:
#    netpublic_redsaber.example:
#        class: %netpublic_redsaber.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
