<?php

namespace Netpublic\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AsignaturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignaturaRepository extends EntityRepository
{
    public function findAreas($grado_id) {
            return $this->getEntityManager()
                ->createQuery("SELECT a FROM NetpublicCoreBundle:Asignatura a WHERE a.grado=:grado_id AND a.es_area=1")                
                ->setParameter('grado_id', $grado_id)
                ->getResult(); 

    }
    public function findAsg($grado_id) {
            return $this->getEntityManager()
                ->createQuery("SELECT a FROM NetpublicCoreBundle:Asignatura a WHERE a.grado=:grado_id AND a.es_area=0")                
                ->setParameter('grado_id', $grado_id)
                ->getResult(); 

    }

}