<?php

namespace Netpublic\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuditoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuditoriaRepository extends EntityRepository
{
        public function getNroReportesAlunmno($alumno_id,$tipo){         
        $query="SELECT count(ps) FROM NetpublicCoreBundle:ProfesorSolicitud ps";
        $query.=" WHERE (ps.alumno=:alumno_id";
        $query.=" AND ps.tipo=:tipo";
        $query.=" )";                          
        $nro=  $this->getEntityManager()->createQuery($query)                
                              ->setParameters(array(
                                       "alumno_id"=>$alumno_id,                                   
                                       "tipo"=>$tipo
                                    ))->getSingleScalarResult();
                             
                             
                            
        return $nro+0;        
    }
    public function hayPublicacionesAuditoriasActivas($tipo=0){
        $em=  $this->getEntityManager();
        $resultado=FALSE;
        $hoy=new \DateTime("now");
        $hoy=$hoy->format("Y-m-d H:i:s");
        $parametros=array("fecha_actual"=>$hoy);
        $query="SELECT count(a) FROM NetpublicCoreBundle:Auditoria a WHERE   ";
        if($tipo!=0){
            $query.="a.tipo=:tipo AND";
            $parametros=array(
                           "fecha_actual"=>$hoy,
                           "tipo"=>$tipo     
              );
        }
        $query.=" a.fecha_inicio<=:fecha_actual"; 
        $query.=" AND a.fecha_final>=:fecha_actual"; 
        $query = $em->createQuery($query)
                            ->setParameters($parametros);
         $count = $query->getSingleScalarResult();
         if($count>0){
             $resultado=true;
         }
         return $resultado;
  }
    public function getPublicacionAuditoriaActiva($tipo=0) {
        $em=  $this->getEntityManager();
        $hoy=new \DateTime("now");
        $hoy=$hoy->format("Y-m-d H:i:s");
        $parametros=array("fecha_actual"=>$hoy);
        $query="SELECT a FROM NetpublicCoreBundle:Auditoria a WHERE   ";
        if($tipo!=0){
            $query.="a.tipo=:tipo AND";
            $parametros=array(
                           "fecha_actual"=>$hoy,
                           "tipo"=>$tipo     
              );
        }
        $query.=" a.fecha_inicio<=:fecha_actual"; 
        $query.=" AND a.fecha_final>=:fecha_actual"; 
        $query = $em->createQuery($query)
                            ->setParameters($parametros);
         $resultado = $query->getResult();
        return $resultado[0];

        
    }

}
