<?php

namespace Netpublic\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CondicioncaColegio
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CondicioncacolegioRepository extends EntityRepository
{
}
