<?php

namespace Netpublic\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CondiciongradoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CondiciongradoRepository extends EntityRepository
{
}
