<?php

namespace Netpublic\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratoRepository extends EntityRepository
{
    public function tieneContrato($profesor_id,$asignatura_id){
        $em=  $this->getEntityManager();
        $query = $em->createQuery('select count(a_d) FROM NetpublicCoreBundle:Contrato a_d where a_d.profesor_contrato=:profesor_id AND a_d.asignatura=:asignatura_id')
                    ->setParameters(array(
                        'profesor_id'=>$profesor_id,
                        'asignatura_id'=>$asignatura_id
                ));
        $count = $query->getSingleScalarResult();
        return $count;
    }
}