<?php

namespace Netpublic\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CriteriopromocionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriteriopromocionRepository extends EntityRepository
{
    public function findCriteriosHabilitar() {
                return $this->getEntityManager()
                ->createQuery("SELECT c FROM NetpublicCoreBundle:CriterioPromocion c WHERE c.tipo=0")
                ->getOneOrNullResult(); 

    }
    public function findCriteriosPerder() {
                return $this->getEntityManager()
                ->createQuery("SELECT c FROM NetpublicCoreBundle:CriterioPromocion c WHERE c.tipo=1")
                ->getOneOrNullResult(); 

    }

}
