<?php

namespace Netpublic\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GrupoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesempenoRepository extends EntityRepository
{
                    
    public function findDesempenosAsignaturaProfe($asignatura,$periodo_id,$grupo,$profesor) {
             $sql="SELECT d FROM NetpublicCoreBundle:Desempeno d ";
             $sql.="JOIN d.grupo g ";
             $sql.="WHERE ";
             $sql.="d.profesor=:profesor_id  ";
             $sql.="AND d.periodo=:periodo_id";             
             $sql.=" AND d.asignatura=:asignatura_id ";
            //$sql.="and d.profesor=:profesor and d.asignatura=:asignatura ";
             $sql.="AND g.id=:grupo_id ";
             $entities=$this->getEntityManager()
                ->createQuery($sql)                
                ->setParameters(array(
                    'profesor_id'=>$profesor,
                    'asignatura_id'=>$asignatura,
                    'grupo_id'=>$grupo,
                    'periodo_id'=>$periodo_id
                    ))
                ->getResult(); 
        return $entities;

        
    }
}