<?php

namespace Netpublic\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GradoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradoRepository extends EntityRepository
{
    public function getHorasNecesariasTodoGrupos(){
        $minutos_semanales_grupo=0;
        $grados=$this->findAll();
        foreach ($grados as $grado) {
            $materias_grados=$grado->getAsignaturas();
            $numero_grupos=count($grado->getGrupo()->toArray());
            foreach ($materias_grados as $materia) {
                if($materia->getEsArea()==FALSE){
                $minutos_semanales=$materia->getDuracionMinutos()*$materia->getFrucuenciaSemana();
                $minutos_semanales_grupo=$minutos_semanales+$minutos_semanales_grupo;
                }
            }
            if($numero_grupos>0)
                 $minutos_semanales_grupo=$numero_grupos*$minutos_semanales_grupo;
            else
                $minutos_semanales_grupo=0;
        }
        return $minutos_semanales_grupo/60;
    }
    
    
}