<?php

namespace Netpublic\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HorarioAulaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorarioAulaRepository extends EntityRepository

{
    public function getHorasDisponiblesAula($asignatura_id,$aula_id){
        $em=  $this->getEntityManager();
        $query = $em->createQuery('select count(a_d) FROM NetpublicCoreBundle:HorarioAula a_d where a_d.aula=:aula_id AND a_d.asignatura=:asignatura_id AND a_d.es_disponible=1')
                    ->setParameters(array(
                        'aula_id'=>$aula_id,
                        'asignatura_id'=>$asignatura_id
                ));
        $count = $query->getSingleScalarResult();
        return $count;
        
    }
    public function setHorarioAula($asignatura_id,$aula_id,$dia,$hora_inicio,$hora_final){
        $em=  $this->getEntityManager();
        $query = $em->createQuery('select a_d FROM NetpublicCoreBundle:HorarioAula a_d where a_d.aula=:aula_id AND a_d.asignatura=:asignatura_id AND a_d.es_disponible=1 AND a_d.dia=:dia  AND a_d.hora_inicio=:hora_inicio  AND a_d.hora_final=:hora_final')
                    
                    ->setParameters(array(
                        'aula_id'=>$aula_id,
                        'asignatura_id'=>$asignatura_id,
                        'dia'=>$dia,
                        'hora_inicio'=>$hora_inicio,
                        'hora_final'=>$hora_final
                ));
        $horarios_aula = $query->getResult();
        $horarios_aula[0]->setEsDisponible(1);
        $em->persist($horarios_aula[0]);
        $em->flush();       
    }
    public function getHorarioAula($asignatura_id,$aula_id,$dia,$hora_inicio,$hora_final){
        $em=  $this->getEntityManager();
        $query = $em->createQuery('select a_d FROM NetpublicCoreBundle:HorarioAula a_d where a_d.aula=:aula_id AND a_d.asignatura=:asignatura_id AND a_d.es_disponible=1 AND a_d.dia=:dia  AND a_d.hora_inicio=:hora_inicio  AND a_d.hora_final=:hora_final')
                    
                    ->setParameters(array(
                        'aula_id'=>$aula_id,
                        'asignatura_id'=>$asignatura_id,
                        'dia'=>$dia,
                        'hora_inicio'=>$hora_inicio,
                        'hora_final'=>$hora_final
                ));
        $horarios_aula = $query->getResult();
        //$horarios_aula[0]->setEsDisponible(0);
        //$em->persist($horarios_aula[0]);
        //$em->flush();       
        return $horarios_aula[0];
    }
    public function generarHorariosAllAulas(){
        return -1;
    }
}