<?php

namespace Netpublic\CoreBundle\Repository;
use Netpublic\CoreBundle\Entity\Mensaje;
use Doctrine\ORM\EntityRepository;
use Netpublic\CoreBundle\Entity\Usuario;

/**
 * mensaje_usuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MensajeUsuarioRepository extends EntityRepository
{
    public function numeroMesanjesNoLeidos(){
        $em = $container->get('doctrine')->getEntityManager();
        $query = $em->createQuery('SELECT count(a) FROM NetpublicCoreBundle:MensajeUsuario a WHERE a.destinatario=:destinatario')
                            ->setParameter(
                            "destinatario",$remitente->getId()  
                            );
                        $count = $query->getSingleScalarResult();
        return $count;                
    }
    public function esDestinatarioMesanje(Mensaje $entity,  Usuario $remitente){
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT count(a) FROM NetpublicCoreBundle:MensajeUsuario a WHERE a.destinatario=:destinatario and a.mensaje=:mensaje_id')
                            ->setParameter(
                            "destinatario",$remitente->getId()  
                            )
                            ->setParameter('mensaje_id', $entity->getId())    ;
                        $count = $query->getSingleScalarResult();
        return $count;                
    }
    
}