<?php

namespace Netpublic\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Netpublic\CoreBundle\Entity\AlumnoDimension;
use Netpublic\CoreBundle\Entity\Grupo;
use Netpublic\CoreBundle\Entity\Asignatura;
/**
 * NotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class NotaRepository extends EntityRepository
{
    public function calificarGrupo($nota_alumnos_dimension,$notas_grupo){ 
        $numero_estudiante=0;
         if(count($nota_alumnos_dimension)==  count($notas_grupo)){
            $numero_estudiante=count($notas_grupo);
         }
         elseif(count($nota_alumnos_dimension)==0 && count($notas_grupo)==0){
             return $numero_estudiante;
         }
         else{
             return $numero_estudiante;
         }
        $em=$this->getEntityManager();
        for ($index = 0; $index < count($nota_alumnos_dimension); $index++) {
            $nota_alumnos_dimension[$index]->setNota($notas_grupo[$index]);
            $em->persist($nota_alumnos_dimension[0]);
        }

        $em->flush();
        return $numero_estudiante;
    }
    public function getNotasProfesor($profesor_id,$padre_id) {
        $query="SELECT a_d,d FROM NetpublicCoreBundle:AlumnoDimension a_d JOIN a_d.dimension d JOIN d.padre p";
        $query.=" WHERE (";
        $query.=" d.profesor=:profesor_id";
        $query.=" AND p.padre=:padre_id";
        $query.=" AND d.tipo=4";
        $query.=" )";                          
        $nro_asg_perdidas=  $this->getEntityManager()->createQuery($query)                
                              ->setParameters(array(
                                            "profesor_id"=>$profesor_id,
                                            "padre_id"=>$padre_id
                               ))->getResult();
                             
                             
        
        return $nro_asg_perdidas;        

        
    }
    

}