<?php

namespace Netpublic\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotaRecuperacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaRecuperacionRepository extends EntityRepository
{
    public function findRecuperacionesAlumno($ano_escolar_id,$alumno_id) {
        $em=  $this->getEntityManager();
            $query="SELECT a_d,n FROM NetpublicCoreBundle:NotaRecuperacion a_d JOIN a_d.nota n";
            $query.=" WHERE";
            $query.=" (";
            $query.=" n.alumno=:alumno_id";
            $query.=" AND a_d.ano_escolar=:ano_escolar_id";
            $query.=" )"; 
            $entities=$em->createQuery($query)                
                                 ->setParameters(array(
                                         "ano_escolar_id"=>$ano_escolar_id,
                                         "alumno_id"=>$alumno_id,
                                          ))->getResult(); 
            return $entities; 
    }
        public function findRecuperacionesAsgAlumno($ano_escolar_id,$alumno_id,$asignatura_id) {
        $em=  $this->getEntityManager();
            $query="SELECT a_d,n FROM NetpublicCoreBundle:NotaRecuperacion a_d JOIN a_d.nota n";
            $query.=" WHERE";
            $query.=" (";
            $query.=" n.alumno=:alumno_id";
            $query.=" AND a_d.ano_escolar=:ano_escolar_id";
            $query.=" AND n.asignatura=:asg_id";
            
            $query.=" )"; 
            $entities=$em->createQuery($query)                
                                 ->setParameters(array(
                                         "ano_escolar_id"=>$ano_escolar_id,
                                         "alumno_id"=>$alumno_id,
                                         "asg_id"=>$asignatura_id
                                         
                                          ))->getResult(); 
            return $entities; 
    }

    public function findNroRecuperacionesAlumno($ano_escolar_id,$alumno_id) {
        $em=  $this->getEntityManager();
            $query="SELECT count(a_d) FROM NetpublicCoreBundle:NotaRecuperacion a_d JOIN a_d.nota n";
            $query.=" WHERE";
            $query.=" (";
            $query.=" n.alumno=:alumno_id";
            $query.=" AND a_d.ano_escolar=:ano_escolar_id";
            $query.=" )"; 
            $entities=$em->createQuery($query)                
                                 ->setParameters(array(
                                         "ano_escolar_id"=>$ano_escolar_id,
                                         "alumno_id"=>$alumno_id,
                                          ))->getSingleScalarResult(); 
            return $entities; 
    }
}
