<?php

namespace Netpublic\CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Netpublic\CoreBundle\Entity\Profesor;
use Netpublic\CoreBundle\Entity\Dimension;
/**
 * ProfesorentregaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
      
class ProfesorperiodoentregaRepository extends EntityRepository
{
    public function tieneTiempoProfesor($periodo_id,$profesor_id) {
        $em=  $this->getEntityManager();
        $result=TRUE;
        $hoy=new \DateTime("now");
        $hoy=$hoy->format("Y-m-d H:i:s");
        $query="SELECT count(a) FROM NetpublicCoreBundle:Profesorperiodoentrega a ";
        $query.="WHERE  a.profesor=:profesor_id";
        $query.=" AND a.periodo=:periodo_id"; 
        $query.=" AND a.fecha_inicio<=:fecha_actual"; 
        $query.=" AND a.fecha_final>=:fecha_actual"; 
        $query = $em->createQuery($query)
                            ->setParameters(array(
                           "periodo_id"=>$periodo_id,
                           "fecha_actual"=>$hoy,
                            "profesor_id"=>$profesor_id    
                            ));
         $count = $query->getSingleScalarResult();
         if($count>0)
             $result=FALSE;
         return $result;
    }
}